from enum import Enum


class Misiones(Enum):
    NOT_SELECTED = 10
    ACCELERATION = 11
    SKIDPAD = 12
    AUTOCROSS = 13
    TRACK_DRIVE = 14
    AUTONOMOUS_DEMO = 15
    ADS_INSPECTION = 16
    ADS_EBS = 17
    DDT_INSPECTION_A = 18
    DDT_INSPECTION_B = 19
    JOYSTICK = 20
    MANUAL = 21
